#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate tests/data/unesco44_table.hpp, and check it against the equation.

The table below is transcribed by hand from a SCANNED 1983 document with no text
layer (UNESCO Technical Papers in Marine Science 44, p. 50), so the transcription
itself needs verifying. Running this module does that: it evaluates the published
Chen & Millero coefficients -- entered separately, from p. 46-47 and the FORTRAN
listing on p. 49 -- against every transcribed value.

A transcription slip shows up as one large outlier rather than a uniform
near-miss, which is exactly what this catches. The measured worst error is
0.0499 m/s over all 220 values, against a table printed to 0.1 m/s: the
agreement is as tight as the published data can express.

    python3 tools/make_unesco_table.py [output.hpp]
"""
import pathlib
import sys

# UNESCO Tech Paper 44 (Fofonoff & Millard 1983) p.50, transcribed from the scan.
# Columns T = 0,10,20,30,40 C (IPTS-68); rows p = 0..10000 dbar; blocks S = 25,30,35,40.
TAB = {
25:[(0,[1435.8,1477.7,1510.3,1535.2,1553.4]),(1000,[1452.0,1494.1,1527.0,1552.1,1570.6]),
    (2000,[1468.6,1510.7,1543.6,1569.0,1587.6]),(3000,[1485.6,1527.5,1560.3,1585.7,1604.5]),
    (4000,[1502.8,1544.3,1576.9,1602.4,1621.3]),(5000,[1520.4,1561.3,1593.6,1619.0,1638.0]),
    (6000,[1538.1,1578.4,1610.3,1635.5,1654.6]),(7000,[1556.0,1595.6,1626.9,1651.9,1671.0]),
    (8000,[1574.1,1612.8,1643.5,1668.2,1687.2]),(9000,[1592.2,1630.1,1660.2,1684.5,1703.3]),
    (10000,[1610.4,1647.4,1676.8,1700.6,1719.2])],
30:[(0,[1442.5,1483.7,1515.9,1540.4,1558.3]),(1000,[1458.8,1500.2,1532.5,1557.3,1575.4]),
    (2000,[1475.4,1516.8,1549.2,1574.1,1592.3]),(3000,[1492.4,1533.6,1565.8,1590.8,1609.2]),
    (4000,[1509.7,1550.4,1582.4,1607.4,1626.0]),(5000,[1527.2,1567.4,1599.1,1624.0,1642.7]),
    (6000,[1544.9,1584.4,1615.7,1640.4,1659.2]),(7000,[1562.7,1601.5,1632.3,1656.8,1675.6]),
    (8000,[1580.7,1618.7,1648.9,1673.1,1691.8]),(9000,[1598.8,1636.0,1665.5,1689.3,1707.8]),
    (10000,[1616.8,1653.3,1682.1,1705.4,1723.5])],
35:[(0,[1449.1,1489.8,1521.5,1545.6,1563.2]),(1000,[1465.5,1506.3,1538.1,1562.4,1580.2]),
    (2000,[1482.3,1523.0,1554.7,1579.2,1597.1]),(3000,[1499.3,1539.7,1571.3,1595.9,1613.9]),
    (4000,[1516.5,1556.5,1587.9,1612.5,1630.7]),(5000,[1534.0,1573.4,1604.5,1629.0,1647.3]),
    (6000,[1551.6,1590.4,1621.0,1645.4,1663.8]),(7000,[1569.4,1607.5,1637.6,1661.7,1680.1]),
    (8000,[1587.2,1624.6,1654.1,1677.9,1696.2]),(9000,[1605.2,1641.8,1670.6,1694.0,1712.2]),
    (10000,[1623.2,1659.0,1687.2,1710.1,1727.8])],
40:[(0,[1455.8,1495.9,1527.1,1550.8,1568.1]),(1000,[1472.3,1512.5,1543.7,1567.6,1585.0]),
    (2000,[1489.1,1529.1,1560.3,1584.3,1601.8]),(3000,[1506.1,1545.8,1576.8,1600.9,1618.6]),
    (4000,[1523.3,1562.5,1593.3,1617.5,1635.3]),(5000,[1540.7,1579.4,1609.8,1633.9,1651.9]),
    (6000,[1558.2,1596.3,1626.3,1650.2,1668.3]),(7000,[1575.9,1613.3,1642.8,1666.5,1684.6]),
    (8000,[1593.7,1630.3,1659.2,1682.6,1700.6]),(9000,[1611.5,1647.4,1675.7,1698.7,1716.4]),
    (10000,[1629.3,1664.6,1692.2,1714.6,1732.0])]}

def svel_1977(S,T,P0):   # UNESCO 44 p.49 FORTRAN, verbatim
    P=P0/10.0; SR=abs(S)**0.5
    D=1.727e-3-7.9836e-6*P
    B1=7.3637e-5+1.7945e-7*T; B0=-1.922e-2-4.42e-5*T; B=B0+B1*P
    A3=(-3.389e-13*T+6.649e-12)*T+1.100e-10
    A2=((7.988e-12*T-1.6002e-10)*T+9.1041e-9)*T-3.9064e-7
    A1=(((-2.0122e-10*T+1.0507e-8)*T-6.4885e-8)*T-1.2580e-5)*T+9.4742e-5
    A0=(((-3.21e-8*T+2.006e-6)*T+7.164e-5)*T-1.262e-2)*T+1.389
    A=((A3*P+A2)*P+A1)*P+A0
    C3=(-2.3643e-12*T+3.8504e-10)*T-9.7729e-9
    C2=(((1.0405e-12*T-2.5335e-10)*T+2.5974e-8)*T-1.7107e-6)*T+3.1260e-5
    C1=(((-6.1185e-10*T+1.3621e-7)*T-8.1788e-6)*T+6.8982e-4)*T+0.153563
    C0=((((3.1464e-9*T-1.47800e-6)*T+3.3420e-4)*T-5.80852e-2)*T+5.03711)*T+1402.388
    C=((C3*P+C2)*P+C1)*P+C0
    return C+(A+B*SR+D*S)*S

HEADER = """// SPDX-License-Identifier: Apache-2.0
// The official UNESCO sound-speed table, transcribed from the primary source.
//
//   Fofonoff, N. P. and Millard, R. C. Jr. (1983), "Algorithms for computation
//   of fundamental properties of seawater", UNESCO Technical Papers in Marine
//   Science 44, Table on p. 50, and the check value on p. 48.
//
// 220 values: salinity 25/30/35/40 PSU, temperature 0/10/20/30/40 C on
// IPTS-68, pressure 0..10000 dbar in steps of 1000.
//
// Printed to 0.1 m/s, so the tolerance a test may demand is 0.05 -- the
// rounding half-width. That is still 40x tighter than the 2 m/s spread between
// the empirical equations, which is why this table catches what mutual
// agreement between them cannot.
//
// Generated by tools/make_unesco_table.py. Do not edit by hand.
#ifndef PHANTOM_TEST_UNESCO_TABLE_HPP
#define PHANTOM_TEST_UNESCO_TABLE_HPP

namespace unesco44 {

struct Entry { double salinity_psu; double temperature_c68; double pressure_dbar; double speed_mps; };

// UNESCO 44 p. 48: "Check Value: 1731.995 m/s for S = 40, t = 40 C,
// p = 10000 decibars".
inline constexpr double kCheckSalinity    = 40.0;
inline constexpr double kCheckTemperature = 40.0;
inline constexpr double kCheckPressure    = 10000.0;
inline constexpr double kCheckSpeed       = 1731.995;

inline constexpr Entry kTable[] = {
"""

FOOTER = """};

inline constexpr int kTableSize = static_cast<int>(sizeof(kTable) / sizeof(kTable[0]));

}  // namespace unesco44

#endif  // PHANTOM_TEST_UNESCO_TABLE_HPP
"""


def verify():
    """Check the transcription against the independently entered coefficients."""
    worst, bad = 0.0, []
    for S, rows in TAB.items():
        for p, vals in rows:
            for i, T in enumerate([0, 10, 20, 30, 40]):
                got = svel_1977(S, T, p)
                d = got - vals[i]
                worst = max(worst, abs(d))
                if abs(d) > 0.05:
                    bad.append((S, T, p, vals[i], got, d))
    n = sum(len(r[1]) for rows in TAB.values() for r in rows)
    print("check value: %.4f   (published 1731.995)" % svel_1977(40, 40, 10000))
    print("%d values, worst |delta| = %.4f m/s (table is printed to 0.1)" % (n, worst))
    for b in bad:
        print("   OUTLIER S=%d T=%d p=%d published=%.1f computed=%.3f d=%+.3f" % b)
    if bad:
        raise SystemExit("transcription does not reproduce the equation")
    if abs(svel_1977(40, 40, 10000) - 1731.995) > 1e-3:
        raise SystemExit("check value not reproduced")
    return n


def emit(path):
    out = [HEADER]
    for S in sorted(TAB):
        out.append("    // salinity %g PSU\n" % S)
        for p, vals in TAB[S]:
            for T, v in zip([0, 10, 20, 30, 40], vals):
                out.append("    {%5.1f, %5.1f, %8.1f, %9.4f},\n" % (S, T, p, v))
    out.append(FOOTER)
    pathlib.Path(path).write_text("".join(out))


if __name__ == "__main__":
    n = verify()
    dst = sys.argv[1] if len(sys.argv) > 1 else "tests/data/unesco44_table.hpp"
    emit(dst)
    print("wrote %d entries -> %s" % (n, dst))
