#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate tests/data/iso9613_table.hpp, and check it against the equations.

Values transcribed from ISO 9613-1:1993 Table 1 (a)(g)(h) -- the published
pure-tone atmospheric-absorption attenuation coefficients in dB/km at one
standard atmosphere. The PDF's text layer is OCR-damaged in places ("lO" for
"10", stray characters), so only cells that could be read unambiguously are
included; a corrupted cell would show up here as a large outlier rather than
silently weakening the test.

The equations below are entered SEPARATELY, from the standard's clauses 6.2 and
annex B, so agreement between them and the table is evidence about both.

    python3 tools/make_iso9613_table.py [output.hpp]
"""
import math
import pathlib
import sys

PR, T0, T01 = 101.325, 293.15, 273.16


def alpha_db_per_km(f_hz, temp_c, rh, p_kpa=PR):
    T = temp_c + 273.15
    psat_over_pr = 10.0 ** (-6.8346 * (T01 / T) ** 1.261 + 4.6151)
    h = rh * psat_over_pr * PR / p_kpa
    pa_pr = p_kpa / PR
    frO = pa_pr * (24.0 + 4.04e4 * h * (0.02 + h) / (0.391 + h))
    frN = pa_pr * (T / T0) ** -0.5 * (
        9.0 + 280.0 * h * math.exp(-4.170 * ((T / T0) ** (-1.0 / 3.0) - 1.0)))
    f2 = f_hz * f_hz
    classical = 1.84e-11 * (1.0 / pa_pr) * (T / T0) ** 0.5
    relax = (T / T0) ** -2.5 * (
        0.01275 * math.exp(-2239.1 / T) / (frO + f2 / frO)
        + 0.1068 * math.exp(-3352.0 / T) / (frN + f2 / frN))
    return 8.686 * f2 * (classical + relax) * 1000.0


def midband(k):
    """Note 5: the table was computed at exact midband frequencies, not the
    preferred nominal values printed in its own row headings."""
    return 1000.0 * 10.0 ** (k / 10.0)


# (band index k, nominal Hz) -> {relative humidity %: published dB/km}
# ISO 9613-1:1993 Table 1 (g), air temperature 10 C.
TABLE_10C = {
    (-13, 50):    {10: 2.62e-1, 20: 1.97e-1, 30: 1.55e-1, 40: 1.26e-1, 50: 1.05e-1,
                   70: 7.85e-2, 80: 6.96e-2, 90: 6.24e-2},
    (-9, 125):    {10: 7.88e-1, 20: 5.79e-1, 30: 5.51e-1, 40: 5.22e-1, 50: 4.86e-1,
                   60: 4.47e-1, 80: 3.78e-1, 90: 3.48e-1, 100: 3.22e-1},
    (-5, 315):    {10: 3.39, 20: 1.62, 30: 1.31, 40: 1.27, 50: 1.28, 60: 1.30,
                   70: 1.31, 80: 1.31, 90: 1.30, 100: 1.29},
    (-3, 500):    {10: 7.52, 20: 3.27, 30: 2.28, 40: 1.98, 50: 1.90, 70: 1.93,
                   80: 1.97, 90: 2.00, 100: 2.03},
    (0, 1000):    {30: 6.77, 40: 5.07, 50: 4.26, 70: 3.66, 80: 3.57, 100: 3.55},
    (2, 1600):    {10: 3.55e1, 20: 2.47e1, 30: 1.55e1, 50: 8.83, 60: 7.52,
                   70: 6.73, 80: 6.23, 90: 5.92, 100: 5.72},
    (3, 2000):    {10: 4.23e1, 20: 3.62e1, 30: 2.35e1, 40: 1.68e1, 50: 1.32e1,
                   80: 8.76, 90: 8.14, 100: 7.71},
    (5, 3150):    {10: 5.32e1, 30: 5.27e1, 40: 3.91e1, 50: 3.06e1, 60: 2.51e1,
                   70: 2.15e1, 80: 1.90e1, 90: 1.71e1, 100: 1.57e1},
    (6, 4000):    {10: 5.73e1, 20: 9.15e1, 30: 7.66e1, 50: 4.67e1, 70: 3.28e1,
                   80: 2.87e1, 90: 2.57e1, 100: 2.35e1},
    (8, 6300):    {10: 6.48e1, 20: 1.35e2, 30: 1.45e2, 40: 1.27e2, 50: 1.06e2,
                   60: 8.94e1, 70: 7.69e1, 80: 6.74e1, 100: 5.44e1},
    (9, 8000):    {10: 6.94e1, 20: 1.54e2, 30: 1.87e2, 40: 1.77e2, 50: 1.55e2,
                   60: 1.34e2, 70: 1.17e2, 80: 1.03e2, 90: 9.24e1, 100: 8.37e1},
    (10, 10000):  {10: 7.59e1, 20: 1.72e2, 30: 2.30e2, 40: 2.37e2, 50: 2.20e2,
                   60: 1.97e2, 70: 1.75e2, 80: 1.57e2, 90: 1.41e2, 100: 1.28e2},
}

HEADER = """// SPDX-License-Identifier: Apache-2.0
// Published atmospheric-absorption coefficients, from the primary source.
//
//   ISO 9613-1:1993, "Acoustics -- Attenuation of sound during propagation
//   outdoors -- Part 1: Calculation of the absorption of sound by the
//   atmosphere", Table 1 (g), air temperature 10 C, one standard atmosphere.
//
// Values are dB/km. The table is printed to three significant figures, so that
// is the tolerance a test may demand.
//
// NOTE 5 of the standard records that the coefficients were computed at the
// EXACT one-third-octave midband frequencies 1000 * 10^(k/10), not the
// preferred nominal values printed in the row headings. `band_index` carries k
// so a test can use the frequency the table was actually built at.
//
// Generated by tools/make_iso9613_table.py. Do not edit by hand.
#ifndef PHANTOM_TEST_ISO9613_TABLE_HPP
#define PHANTOM_TEST_ISO9613_TABLE_HPP

namespace iso9613 {

struct Entry {
    int    band_index;              // k, for f = 1000 * 10^(k/10)
    double nominal_frequency_hz;    // as printed in the table's row heading
    double temperature_c;
    double relative_humidity_pct;
    double attenuation_db_per_km;
};

inline constexpr Entry kTable[] = {
"""

FOOTER = """};

inline constexpr int kTableSize = static_cast<int>(sizeof(kTable) / sizeof(kTable[0]));

}  // namespace iso9613

#endif  // PHANTOM_TEST_ISO9613_TABLE_HPP
"""


def verify():
    worst, worst_at, n, bad = 0.0, None, 0, []
    for (k, nom), row in sorted(TABLE_10C.items()):
        f = midband(k)
        for rh, published in sorted(row.items()):
            got = alpha_db_per_km(f, 10.0, rh)
            rel = abs(got - published) / published
            n += 1
            if rel > worst:
                worst, worst_at = rel, (nom, rh, published, got)
            if rel > 0.005:
                bad.append((nom, rh, published, got, rel))
    print("%d published values, worst relative error %.3f%%" % (n, 100 * worst))
    print("   at %d Hz, %d%% RH: published %.4g, computed %.4g" % worst_at)
    for b in bad:
        print("   OUTLIER %d Hz %d%% published %.4g computed %.4g (%.1f%%)"
              % (b[0], b[1], b[2], b[3], 100 * b[4]))
    if bad:
        raise SystemExit("transcription or equations disagree beyond table precision")
    return n


def emit(path):
    out = [HEADER]
    for (k, nom), row in sorted(TABLE_10C.items()):
        for rh, v in sorted(row.items()):
            out.append("    {%4d, %9.1f, %6.1f, %6.1f, %12.6g},\n" % (k, nom, 10.0, rh, v))
    out.append(FOOTER)
    pathlib.Path(path).write_text("".join(out))


if __name__ == "__main__":
    n = verify()
    dst = sys.argv[1] if len(sys.argv) > 1 else "tests/data/iso9613_table.hpp"
    emit(dst)
    print("wrote %d entries -> %s" % (n, dst))
